### ISSUE TITLE
Support more types of searches

### ISSUE THREAD

**Issue by cibinmathew** [plainas/icl#6] opened 2021-04-16 16:28 UTC
Support more types of comment-command pairs that can be listed in the suggestions

It seems currently only below is supported
```
# first line should be a comment line
This line will be pasted if selected as a match
```

1.  Support group comment followed by multiple lines
eg: on searching --> 'git tricks modified'  show the top comment followed 'git ls-files --modified'
```
# git ls tricks
git ls-files
git ls-files  --modified 
```

2. Support lines without a preceding comment(comment can be on same line towards the end)
eg:
```
git ls-files --modifed  # git trick list modified files only

```

Thoughts and other useful scenarios?

**Comment by plainas** [comment] 2021-04-20 07:19
Hello!
While there is nothing technically wrong with such ideas, they do depart from the philosophy of keeping things as simple as possible. A comment syntax like in example 2, would require either to disallow the comment opening char or requiring an escape sequence for it. Which could become messy  if for example you're grepping for that char. I think the best strategy is to steer clear any parsing rules that go beyond treating lines of text as raw text blobs.

This is stuff that gets inserted into your shell prompt, to be executed seconds after with a keypress. Tricky escaping should be eliminated by design. Shells have enough corner cases already with quoting and escaping.

Similar reasoning can be applied to example 1. Which of the two commands should be used? How does the user pick?

I think it is best to leave the the format trivial so it  can be learned in one minute. Making it straightforward for example, for a developer to re-implement this project in one afternoon.

**Comment by cibinmathew** [comment] 2021-04-20 20:12
Regarding example 1
How about 2 results. One with comment and first line, second with same comment and second line (top comment is logically describing both the commands below it)

**Comment by plainas** [comment] 2022-05-18 22:20
I am going to close this as I think the current format is the most simple/straightforward.

I realize I didn't include a license file in this project. I will license this with the MIT license. Feel free to fork the project.

**Closed as completed by plainas** 2022-05-18 22:20 UTC
